### ISSUE TITLE
Different result with multiple benchmarks

### ISSUE THREAD

**Issue by Nevro** [evanwashere/mitata#52]
Benchmark:
```javascript
import { run, bench, group, summary, do_not_optimize } from '/storage/git/js/mitata/src/main.mjs';

const sizes = [4096, 16386];

function generateBuffers(size) {
    const target = new Uint8Array(Array.from({ length: size }, () => 
        Math.floor(Math.random() * 255))).buffer;
    return { target, source: target.slice(0) };
}

function unit8(target, source) {
    if (target.byteLength !== source.byteLength)
        return false;
    target = new Uint8Array(target), source = new Uint8Array(source);
    for (let index = target.length - 1; index >= 0; index--)
        if (target[index] !== source[index])
            return false;
    return true;
}

function aligned(target, source) {
    const targetByteLength = target.byteLength;
    if (targetByteLength !== source.byteLength)
        return false;
    switch (targetByteLength % 4) {
        default:
            target = new Uint8Array(target), source = new Uint8Array(source);
            break;
        case 2:
            target = new Uint16Array(target), source = new Uint16Array(source);
            break;
        case 0:
            target = new Uint32Array(target), source = new Uint32Array(source);
            break;
    }
    for (let index = target.length - 1; index >= 0; index--)
        if (target[index] !== source[index])
            return false;
    return true;
}

const functions = {
    'Unit8': unit8,
    'aligned': aligned,
};

for (const size of sizes) {
    group(`Buffer size: ${size}`, () => {
        summary(() => {
            const { target, source } = generateBuffers(size);
            for (const { 0: name, 1: callback } of Object.entries(functions)) {
                bench(name, () => {
                    const result = callback(target, source);
                    if (result !== true)
                        throw Error(`return = '${result}'`);
                    return do_not_optimize(result);
                }).compact();
            }
        });
    });
}

await run();
```

Result with multiple sizes: (sizes = [4096, 16386])
```
clk: ~3.83 GHz
cpu: AMD Ryzen 5 3600 6-Core Processor
runtime: bun 1.2.0 (x64-linux)

benchmark                   avg (min … max) p75 / p99    (min … top 1%)
------------------------------------------- -------------------------------
• Buffer size: 4096
------------------------------------------- -------------------------------
Unit8                          2.20 µs/iter   2.19 µs   2.74 µs ▄█▃▁▁▂▁▁▁▁▁
aligned                      616.37 ns/iter 632.05 ns   1.00 µs █▃▃▁▁▁▁▁▁▁▁

summary
  aligned
   3.57x faster than Unit8

• Buffer size: 16386
------------------------------------------- -------------------------------
Unit8                          8.33 µs/iter   8.38 µs   8.56 µs ▂█▁▃▂▂▂▂▁▁▂
aligned                       30.84 µs/iter  30.99 µs  31.24 µs █▁█▁▁▅██▁▁█

summary
  Unit8
   3.7x faster than aligned
```
Result with one size: (sizes = [16386])
```
clk: ~3.97 GHz
cpu: AMD Ryzen 5 3600 6-Core Processor
runtime: bun 1.2.0 (x64-linux)

benchmark                   avg (min … max) p75 / p99    (min … top 1%)
------------------------------------------- -------------------------------
• Buffer size: 16386
------------------------------------------- -------------------------------
Unit8                          8.25 µs/iter   8.27 µs   8.33 µs ▃▂█▁▁▂▂▃▁▂▂
aligned                        4.31 µs/iter   4.15 µs   7.36 µs █▁▁▁▁▁▁▁▁▁▁

summary
  aligned
   1.91x faster than Unit8
```

What's going on here? Am I doing something wrong? Same result with almost all engines (v8, jsc, ~~qjs~~,...)

Edit:
QuickJS excluded! Behaves as expected!

**Comment by evanwashere** [comment]
your code has lots of bugs and cpu cache anti-patterns like reading array backwards, I fixed everything and made proper example [examples/memcmp.js](https://github.com/evanwashere/mitata/blob/a48ad442c754db3e99af527bd61fd70a97efebeb/examples/memcmp.js)

**Comment by observ33r** [comment]
My input is buffer, not casted TypedArray.  Cpu cache and anti-patterns bugs if we running code jitless, but we never do that ;)

```
clk: ~3.95 GHz
cpu: AMD Ryzen 5 3600 6-Core Processor
runtime: node 23.8.0 (x64-linux)

benchmark                   avg (min … max) p75 / p99    (min … top 1%)
------------------------------------------- -------------------------------
• Buffer size: 16386
------------------------------------------- -------------------------------
byte                          11.22 µs/iter  11.34 µs  11.39 µs ▆█▁▁▃▁▁▁▃▁▃
swar                          13.71 µs/iter  13.49 µs  20.51 µs █▁▁▁▁▁▁▁▁▁▁
aligned                        9.10 µs/iter   9.13 µs   9.16 µs ▆█▃▆▆▁▁▆▃▁▃

summary
  aligned
   1.23x faster than byte
   1.51x faster than swar
```

https://github.com/evanwashere/mitata/blob/00a7adcdfc3c8736a42d89d6bc8d723dd436c9c5/examples/memcmp.js#L45

Here you comparing just last index..

I want result grouped by size and no matter how I wrap benchmarks, problem is still a same.

**Comment by evanwashere** [comment]
> Cpu cache and anti-patterns bugs if we running code jitless, but we never do that ;)

jit can't reverse array iteration


> Line 45 in [00a7adc](/evanwashere/mitata/commit/00a7adcdfc3c8736a42d89d6bc8d723dd436c9c5)
> Here you comparing just last index..

it's for slices whose size isn't multiple of 4

> I want result grouped by size and no matter how I wrap benchmarks, problem is still a same.

can't replicate the results with my example
I only see noise introduced by cpu cache pressure and monomorphic optimization (outside of what mitata can control)

```js
clk: ~2.58 GHz
cpu: Apple M1 Pro
runtime: node 23.6.0 (arm64-darwin)

benchmark                   avg (min … max) p75 / p99    (min … top 1%)
------------------------------------------- -------------------------------
byte (16386)                  24.19 µs/iter  25.32 µs    █                 
                      (21.61 µs … 30.42 µs)  26.07 µs ▅ ▅█▅    ▅ ▅▅    ▅ ▅▅
                    (  0.16  b …   1.38  b)   0.29  b █▁███▁▁▁▁█▁██▁▁▁▁█▁██
                  4.47 ipc (  0.19% stalls)  99.79% L1 data cache
         68.07k cycles 304.47k instructions  18.91% retired LD/ST ( 57.59k)

swar (16386)                   2.89 µs/iter   2.83 µs    █                 
                      (2.71 µs … 172.46 µs)   3.54 µs   ▅█                 
                    (240.00  b … 159.16 kb) 299.38  b ▁▂██▃▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
                  5.70 ipc (  0.08% stalls)  99.23% L1 data cache
         12.70k cycles  72.38k instructions  14.16% retired LD/ST ( 10.25k)

------------------------------------------- -------------------------------
byte (4096)                    4.84 µs/iter   4.38 µs █                    
                        (4.31 µs … 8.21 µs)   8.18 µs █                    
                    (  0.16  b …   1.33  b)   0.22  b █▁▁▂▂▁▁▂▁▁▁▁▂▁▂▁▁▁▁▁▂
                  5.51 ipc (  0.04% stalls)  99.98% L1 data cache
         15.79k cycles  86.99k instructions  26.16% retired LD/ST ( 22.76k)

byte (16386)                  17.32 µs/iter  17.24 µs     ██               
                      (17.20 µs … 18.30 µs)  17.27 µs ▅  ▅██  ▅ ▅▅       ▅▅
                    (  0.18  b …   0.18  b)   0.18  b █▁▁███▁▁█▁██▁▁▁▁▁▁▁██
                  4.42 ipc (  0.01% stalls)  99.99% L1 data cache
         55.87k cycles 247.02k instructions  15.07% retired LD/ST ( 37.22k)

swar (4096)                  855.96 ns/iter 861.03 ns        █             
                      (739.98 ns … 1.18 µs)   1.08 µs        █             
                    ( 31.95  b … 378.09  b) 208.56  b ▂▂▁▁▁▁▁█▄▄▁▁▁▁▁▁▁▁▁▁▁
                  6.67 ipc (  0.53% stalls)  99.75% L1 data cache
          2.77k cycles  18.45k instructions  25.22% retired LD/ST (  4.65k)

swar (16386)                   5.30 µs/iter   5.38 µs                  █   
                       (2.75 µs … 69.83 µs)   5.67 µs                  █▆  
                    (240.00  b … 137.60 kb) 319.80  b ▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██▃▁
                  6.65 ipc (  0.08% stalls)  99.88% L1 data cache
         20.45k cycles 136.03k instructions  36.14% retired LD/ST ( 49.15k)
```

and disabling jit removes noise introduced by monomorphic optimization:
```js
clk: ~0.04 GHz
cpu: Apple M1 Pro
runtime: node 23.6.0 (arm64-darwin)

benchmark                   avg (min … max) p75 / p99    (min … top 1%)
------------------------------------------- -------------------------------
byte (16386)                 349.77 µs/iter 336.63 µs █                    
                    (327.83 µs … 803.21 µs) 718.08 µs █                    
                    (864.00  b …   1.44 kb) 960.74  b █▆▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
                  6.30 ipc (  0.05% stalls)  99.99% L1 data cache
          1.10M cycles   6.96M instructions  38.43% retired LD/ST (  2.67M)

swar (16386)                  79.82 µs/iter  78.29 µs  █                   
                     (77.25 µs … 208.04 µs) 100.75 µs  █                   
                    (  1.14 kb …   1.24 kb)   1.16 kb ▁█▁▂▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁
                  6.82 ipc (  0.04% stalls)  99.98% L1 data cache
        260.23k cycles   1.77M instructions  37.88% retired LD/ST (671.98k)

------------------------------------------- -------------------------------
byte (4096)                   84.88 µs/iter  80.67 µs █                    
                     (79.00 µs … 256.38 µs) 176.46 µs █                    
                    (864.00  b …   1.44 kb) 960.42  b █▃▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
                  6.44 ipc (  0.04% stalls)  99.99% L1 data cache
        272.20k cycles   1.75M instructions  38.27% retired LD/ST (670.86k)

byte (16386)                 326.76 µs/iter 325.25 µs    █                 
                    (315.25 µs … 374.29 µs) 356.42 µs   ▃█▂                
                    (960.00  b …   0.98 kb) 960.31  b ▁▁███▂▂▂▂▂▁▁▁▁▂▁▁▆▁▂▁
                  6.53 ipc (  0.00% stalls) 100.00% L1 data cache
          1.06M cycles   6.92M instructions  38.65% retired LD/ST (  2.67M)

swar (4096)                   20.49 µs/iter  20.38 µs      █             █ 
                      (19.84 µs … 24.53 µs)  20.43 µs ▅  ▅ █▅  ▅▅ ▅      █▅
                    (208.28  b … 208.29  b) 208.28  b █▁▁█▁██▁▁██▁█▁▁▁▁▁▁██
                  6.77 ipc (  0.04% stalls)  99.99% L1 data cache
         65.58k cycles 443.90k instructions  38.09% retired LD/ST (169.08k)

swar (16386)                  78.61 µs/iter  78.17 µs  █                   
                     (77.63 µs … 102.13 µs)  89.13 µs  █                   
                    (  1.14 kb …   1.24 kb)   1.16 kb ▁█▁▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁
                  6.88 ipc (  0.02% stalls)  99.99% L1 data cache
        257.78k cycles   1.77M instructions  37.92% retired LD/ST (671.98k)
```

**Comment by observ33r** [comment]
My mistake. I set the aligned index to 0... not even realize what was happening! Everything is crystal clear now and behaves as expected.

Thanks for your effort and time!!

I managed to squeeze even little more..
```js
clk: ~3.97 GHz
cpu: AMD Ryzen 5 3600 6-Core Processor
runtime: node 23.8.0 (x64-linux)

benchmark                   avg (min … max) p75 / p99    (min … top 1%)
------------------------------------------- -------------------------------
uint8 (16)                    60.28 ns/iter  58.05 ns ▄█                   
                     (55.95 ns … 144.09 ns)  88.28 ns ██                   
                    (244.33  b … 599.04  b) 464.27  b ██▄▁▁▁▁▁▁▁▁▁▁▁▄▃▁▁▁▁▁
                   3.97 ipc ( 96.01% cache)    0.02 branch misses
         247.57 cycles  983.52 instructions   15.65 c-refs    0.62 c-misses

uint8 (512)                    1.69 µs/iter   1.92 µs                   █  
                      (767.59 ns … 2.10 µs)   2.05 µs                 ▂▄█▂ 
                    (392.42  b … 403.67  b) 400.07  b ▄▂▂▁▃▃▁▃▄▇▅▄▁▄▂█████▂
                   3.03 ipc ( 72.59% cache)    4.83 branch misses
          5.28k cycles  15.99k instructions  118.04 c-refs   32.36 c-misses

uint8 (4096)                   5.25 µs/iter   5.91 µs  ▅                 █ 
                        (4.17 µs … 8.78 µs)   6.02 µs  █▆               ██ 
                    (  9.91  b … 400.18  b) 205.05  b ███▁▄▄▁▁▁▁▁▁▁▁▁▁▁▁███
                   4.49 ipc ( 84.84% cache)   11.22 branch misses
         20.64k cycles  92.69k instructions  480.26 c-refs   72.82 c-misses

uint8 (16386)                 13.38 µs/iter  13.45 µs     █                
                      (13.25 µs … 13.51 µs)  13.50 µs ▅ ▅ █       ▅▅ ▅    ▅
                    ( 13.18  b …  51.51  b)  36.88  b █▁█▁█▁▁▁▁▁▁▁██▁█▁▁▁▁█
                   4.90 ipc ( 92.87% cache)   19.78 branch misses
         53.21k cycles 260.52k instructions   2.63k c-refs  187.24 c-misses

swar (16)                     60.44 ns/iter  59.78 ns   █                  
                     (55.36 ns … 142.11 ns)  84.81 ns   ██                 
                    ( 60.45  b … 313.06  b) 208.21  b ▁▅██▄▁▁▁▁▁▁▁▁▁▁▁▁▂▂▁▁
                   3.68 ipc ( 95.46% cache)    0.02 branch misses
         247.81 cycles  911.65 instructions    7.14 c-refs    0.32 c-misses

swar (512)                   150.32 ns/iter 149.90 ns          █           
                    (126.52 ns … 192.64 ns) 174.82 ns          █▃          
                    ( 37.67  b … 332.77  b) 208.38  b ▁▁▁▁▁▁▁▁▁██▂▁▁▁▁▁▁▁▂▁
                   4.74 ipc ( 95.37% cache)    0.26 branch misses
         616.22 cycles   2.92k instructions    7.23 c-refs    0.33 c-misses

swar (4096)                  811.71 ns/iter 828.54 ns                  █   
                    (627.19 ns … 870.78 ns) 855.61 ns                  ██  
                    (201.55  b … 342.02  b) 208.78  b ▃▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁██▂▃
                   5.19 ipc ( 94.56% cache)    1.03 branch misses
          3.32k cycles  17.26k instructions    7.99 c-refs    0.43 c-misses

swar (16386)                   2.91 µs/iter   3.15 µs                    █ 
                        (2.33 µs … 3.18 µs)   3.18 µs ▂                  █ 
                    (199.86  b … 213.35  b) 208.02  b █▃▁▁▁▁▁▁▁▁▁▁▁▂▁▁▁▁▁█▅
                   5.44 ipc ( 99.86% cache)    1.06 branch misses
         11.89k cycles  64.67k instructions  510.95 c-refs    0.74 c-misses

equals (16)                    5.29 ns/iter   5.24 ns   █                  
                       (5.11 ns … 44.60 ns)   6.33 ns   █                  
                    (  0.01  b …  32.11  b)   0.06  b ▁██▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
                   4.29 ipc ( 99.22% cache)    0.01 branch misses
          22.21 cycles   95.32 instructions    0.06 c-refs    0.00 c-misses

equals (512)                 126.27 ns/iter 125.18 ns   █                  
                    (121.33 ns … 198.79 ns) 154.37 ns  ▇█                  
                    (113.13  b … 359.93  b) 208.35  b ▂██▆▁▂▂▁▁▁▁▁▁▁▁▁▂▁▁▁▁
                   5.06 ipc ( 95.26% cache)    0.02 branch misses
         522.39 cycles   2.64k instructions    7.22 c-refs    0.34 c-misses

equals (4096)                629.54 ns/iter 627.97 ns ▂█                   
                      (617.98 ns … 1.08 µs) 735.10 ns ██                   
                    (201.29  b … 463.43  b) 209.82  b ███▃▁▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁
                   5.83 ipc ( 94.16% cache)    1.02 branch misses
          2.60k cycles  15.19k instructions    7.83 c-refs    0.46 c-misses

equals (16386)                 2.33 µs/iter   2.33 µs    ██▆               
                        (2.31 µs … 2.37 µs)   2.36 µs  ▇▇████▇             
                    (199.57  b … 212.15  b) 207.91  b ████████▃▃▆▁▃▃▃▃▃▁▃▁▆
                   6.06 ipc ( 99.86% cache)    1.04 branch misses
          9.63k cycles  58.36k instructions  506.10 c-refs    0.72 c-misses

                             ┌                                            ┐
               uint8 ($size)                                            ⢠⠊ 13.38 µs
                swar ($size)                                           ⡔⠁ 
              equals ($size)                                         ⢠⠊   
                                                                    ⡔⠁    
                                                                  ⡠⠊      
                                                                ⢀⠔⠁       
                                                               ⡠⠊         
                                                             ⢀⠔⠁          
                                                            ⡠⠊            
                                                          ⣀⠔⠁             
                                                      ⢀⡠⠔⠉                
                                                   ⣀⠤⠊⠁                   
                                               ⢀⡠⠔⠊                   ⣀⡠⠤⠒
                                            ⣀⠤⠒⠁                ⢀⣀⠤⢒⣊⠭⠤⠒⠒⠉
                                    ⢀⣀⡠⠤⠒⠒⠉⠉             ⣀⣀⣀⣤⣔⠶⠭⠓⠊⠉⠁      
                              ⣀⣤⣤⣒⣒⣉⣁⡠⠤⠤⠤⠤⠤⠤⠤⠤⠤⠶⠖⠒⠒⠒⠛⠛⠛⠋⠉⠉⠉⠉               5.29 ns
                             └                                            ┘

summary
  equals ($size)
   +1.25…+11.43x faster than swar ($size)
   +5.75…+11.4x faster than uint8 ($size)
```

```js
...
if (tor === ArrayBuffer || tor === SharedArrayBuffer)
    target = new Uint8Array(target), source = new Uint8Array(source);
if (isView(target)) {
    const targetLength = target.length;
    if (targetLength !== source.length)
        return false;
    const aligned = targetLength & ~3;
    if (targetLength > 64 && aligned) {
        const length = (targetLength / 4) | 0;
        const target32 = new Int32Array(target.buffer, target.byteOffset, length);
        const source32 = new Int32Array(source.buffer, source.byteOffset, length);
        for (let index = 0; index < length; ++index)
            if (target32[index] !== source32[index])
                return false;
    }
    for (let index = aligned; index < targetLength; ++index)
        if (target[index] !== source[index]) 
            return false;
    return true;
}
...
```
